language: go
before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
  - go vet ./...
  - env GOOS=linux ARCH=amd64 go build ./widgets-api.go
  - mkdir ./build
  - zip ./build/widgets-api.zip widgets-api

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: releases-widgets-api
  skip_cleanup: true
  region: us-east-1
  local_dir: build
